Fixes a missing 'echo' command

diff --git a/runcoms/zshrc b/runcoms/zshrc
--- a/runcoms/zshrc
+++ b/runcoms/zshrc
@@ -55,6 +55,7 @@ BASE16_SHELL="$DOTDIR/base16-shell/"
         eval "$("$BASE16_SHELL/profile_helper.sh")"
 
 # Python: managed by pyenv on macOS
+# TODO: this should be set also for Linux machines
 if [[ $(uname) == 'Darwin' ]]; then
    if command -v pyenv 1>/dev/null 2>&1; then
       eval "$(pyenv init -)"
@@ -65,5 +66,5 @@ fi
 # Source the first alias/abbrev/env file found. Look up in the follwing order: ${HOME}, ${DOTDIR}/zsh
 
 for file in .aliases.zsh .abbrevs.zsh .env.zsh; do
-    if [ -f "$HOME/$file" ]; then source "$HOME/$file"; else "WARNING: '$file' not found. Did you run 'dot set'?" >&2; fi
+    if [ -f "$HOME/$file" ]; then source "$HOME/$file"; else echo "WARNING: '$file' not found. Did you run 'dot set'?" >&2; fi
 done
